POST http://localhost:3000/SV6/MastersItems/SubTableOnObj/Insert/AsIs/{RowIndex}/{KeyName}
Content-Type: application/json

{
  "Category": "",
  "ItemName": "",
  "Pcs": "",
  "WashType": "",
  "DryWashRate": ""
}