POST http://localhost:3000/SV5/MastersCustomers/InsertWithChecks/ForUnique
Content-Type: application/json

{
  "MastersCustomers": "",
  "Mobile": "",
  "DOB": "",
  "GSTNumber": "",
  "City": "",
  "Occupation": "",
  "CompanyName": "",
  "BranchName": ""
}