POST http://localhost:3000/V6/BranOrdersOngole/AddWithDefault/AddFromDefaultObj
Content-Type: application/json

{
  "ItemsInOrder": "",
  "CustomerData": "",
  "OrderData": "",
  "AddOnData": "",
  "CheckOutData": ""
}