POST http://localhost:3000/V6/MastersCustomers/SubTable/Alter/WithPk/{RowPk}/{KeyName}/{pk}
Content-Type: application/json

{
  "MastersCustomers": "",
  "Mobile": "",
  "DOB": "",
  "GSTNumber": "",
  "City": "",
  "Occupation": "",
  "CompanyName": "",
  "BranchName": ""
}