POST http://localhost:3000/V6/BranOrdersKKD/SubTable/Alter/WithPk/{RowPk}/{KeyName}/{pk}
Content-Type: application/json

{
  "ItemsInOrder": "",
  "CustomerData": "",
  "OrderData": "",
  "AddOnData": "",
  "CheckOutData": ""
}