POST http://localhost:3000/V6/BranOrdersOngole/SubTable/Insert/AsIs/{RowIndex}/{KeyName}
Content-Type: application/json

{
  "ItemsInOrder": "",
  "CustomerData": "",
  "OrderData": "",
  "AddOnData": "",
  "CheckOutData": ""
}