POST http://localhost:3000/V6/BranOrdersKKD/SubTableOnArray/Insert/WithUuIdAndDT/{RowIndex}/{KeyName}
Content-Type: application/json

{
  "ItemsInOrder": "",
  "CustomerData": "",
  "OrderData": "",
  "AddOnData": "",
  "CheckOutData": ""
}