POST http://localhost:3000/SV6/BranOrdersKKD/InsertWithChecks/ForUnique
Content-Type: application/json

{
  "ItemsInOrder": "",
  "CustomerData": "",
  "OrderData": "",
  "AddOnData": "",
  "CheckOutData": ""
}