POST http://localhost:3000/SV6/BranOrdersOngole/Alter/ColumnsWithPk/{pk}
Content-Type: application/json

{
  "ItemsInOrder": "",
  "CustomerData": "",
  "OrderData": "",
  "AddOnData": "",
  "CheckOutData": ""
}